name: AWS S3 boto3 example1
on:
  workflow_dispatch:
    inputs:
      enter_bucket_name:
        type: string
        required: true
      enter_region_name:
        type: string
        required: false
        default: 'us-east-1'

jobs:
  s3-boto3-gha-example1:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: AWS privilege 
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::${{ secrets.ACC_NO }}:role/sgha-oidcint
            aws-region: us-east-1

      - name: S3 boto3 example1
       # uses: ./.github/actions/s3-boto3-example1
        uses: comoidcorg/aws-boto3-actions/.github/actions/s3-boto3-example1@main
        with:
          bucket: "${{ github.event.inputs.enter_bucket_name }}"
          bucket-region: "${{ github.event.inputs.enter_region_name }}"
  
  print-deploy-result:
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy output
        run: |
          echo "${{ needs.s3-boto3-gha-example1.outputs.Bucketn }}"
          echo "${{ needs.s3-boto3-gha-example1.outputs.Regionn }}"
    
      
      
    

